config/routes.rb
Rails.application.routes.draw do
  
 
  
  # devise_for :bootstrap3s
  resources :test_questions
  resources :questions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # root 'users#index'
  # root :to => redirect('/test_questions')

  get 'sessions/new'
  get 'users/new'
  get 'questions/feedback'
  get 'questions/answer'
  
  root 'visitors#index'
  # get    '/help',    to: 'static_pages#help'
  # get    '/signup',  to: 'users#new'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  devise_for :users
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  
  def set_admin
    self.role = :admin
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # before_save { self.email = email.downcase }
  # validates :name,  presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: { maximum: 255 },
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  # # has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }
  
  # # Returns the hash digest of the given string.
  # def User.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Devise::Controllers::Helpers
  before_action :authenticate_user!
  before_action :admin_only, :except => :show
  def show
    @user = User.find(params[:id])
    # unless current_user.admin?
      # unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      # end
    #end
  end
  
  def index
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params) #change new to create!
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = "Welcome to the Self Evaluation System!"
      redirect_to @user
      # We can also redirect to home page with a success message
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end  
    
    def admin_only
      # unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      # end
    end
    
    def secure_params
      params.require(:user).permit(:role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<title>Sign up</title>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>      
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <h1>
          User Details:<br><br>
          <%= @user.name %><br>
          <%= @user.email %>
        </h1>
    </section>
  </aside>
</div>