config/routes.rb
Rails.application.routes.draw do
  
 
  
  # devise_for :bootstrap3s
  resources :test_questions
  resources :questions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # root 'users#index'
  # root :to => redirect('/test_questions')

  get 'sessions/new'
  get 'users/new'
  get 'questions/feedback'
  get 'questions/answer'
  
  root 'visitors#index'
  # get    '/help',    to: 'static_pages#help'
  # get    '/signup',  to: 'users#new'
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
  
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to "Take the test!", test_questions_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  
<% end %>
<% if user_signed_in? %>
  <li><%= link_to "Add Questions", questions_path %></li>
  <li><%= link_to 'Users', users_path %></li>
  <% if current_user.admin? %>
    
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--<li>(<) %= link_to 'About', page_path('about') %></li>-->
<!--<)% content_for :title do %>About<)% end %>-->
<!--<h3>About the Website</h3>-->
<!--<p>-->
<!--This web application was created with-->
<!--<)%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>-->
<!--from the <)%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.-->
<!--</p>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Self Evaluation System</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Self Evaluation System", root_path, id: "logo" %>
        <nav>
          <%= render 'layouts/navigation' %>
          <!--<ul class="nav navbar-nav navbar-right">-->
            
          <!--  <li><)%= link_to "Home",  root_path %></li>-->
          <!--  <li>(<)%= link_to "Help",  help_path %></li>-->
          <!--  <()% if logged_in? %>-->
          <!--    <li><)%= link_to "Take the test!", test_questions_path %></li>-->
          <!--    <li><)%= link_to "Add", questions_path %></li>-->
          <!--    <li><)%= link_to "Users", users_path %></li>-->
          <!--    <li class="dropdown">-->
          <!--      <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
          <!--        Account <b class="caret"></b>-->
          <!--      </a>-->
          <!--      <ul class="dropdown-menu">-->
          <!--        <li><)%= link_to "Profile", current_user %></li>-->
          <!--        <li><)%= link_to "Settings", '#' %></li>-->
          <!--        <li class="divider"></li>-->
          <!--        <li>-->
          <!--          <)%= link_to "Log out", logout_path, method: :delete %>-->
          <!--        </li>-->
          <!--      </ul>-->
          <!--    </li>-->
          <!--  <)% else %>-->
          <!--    <li><)%= link_to "Log in", login_path %></li>-->
          <!--  <)% end %>-->
          <!--</ul>-->
        </nav>
      </div>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>